all:
  hosts:
    runner-server:
      ansible_host: 89.167.20.45
      ansible_user: root
  vars:
    gitlab_url: https://gitlab.com
    gitlab_runner_token: glrt-JMQZiF5GZvK0Mo1tclU5zGc6MjA1cG54Cm86MQp0OjIKdTppNWtzFw.01.1i0qmeoa8
    gitlab_runner_executor: docker
    gitlab_runner_docker_image: "alpine:latest"
    gitlab_runner_name: "runner-server"
    gitlab_runner_tags:
      - preview
    preview_server_host: 65.108.243.53
    preview_server_user: preview-user
